FROM node:15.12.0-alpine3.10 as build-stage

WORKDIR /app

COPY ./server ./server

WORKDIR /app/server

RUN npm install -s

RUN npm run build

FROM node:15.12.0-alpine3.10 as release

ENV REGION="dev"

WORKDIR /app

COPY --from=build-stage /app/dist ./dist

WORKDIR /app/dist

COPY package*.json ./

COPY ecosystem.config.js ./

RUN npm install --only=production -s

RUN npm install pm2 -g

EXPOSE 3000

CMD npm run start -- --env $REGION