version: '3.7'

services:
  database:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "CorrectHorseBatteryStapleFor_"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "dev"
    depends_on:
      - "database"
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "dev"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
