FROM microsoft/mssql-server-linux:2017-latest

RUN mkdir -p /scripts
WORKDIR /scripts

COPY ./scripts/ .

RUN chmod +x ./run-initialization.sh

ENV SA_PASSWORD CorrectHorseBatteryStapleFor_
ENV ACCEPT_EULA Y
ENV MSSQL_PID Express

EXPOSE 1433

CMD /bin/bash ./entrypoint.sh